/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;

/**
 *
 * @author Usman
 */
public class addCourseframe extends javax.swing.JFrame {

    /** Creates new form addCourseframe */
    private DBConnect conobject= DBConnect.getInstance();
    GlobalClass gc = new GlobalClass();
    
    
    public addCourseframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clist = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adbutton = new javax.swing.JButton();
        cname = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        ccode = new javax.swing.JTextField();
        chr = new javax.swing.JTextField();
        csem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        csec = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Roll No: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 12, 52, 13);

        rolinput.setText("..");
        getContentPane().add(rolinput);
        rolinput.setBounds(70, 10, 66, 14);

        clist.setBackground(new java.awt.Color(153, 204, 255));
        clist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(clist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 53, 334, 250);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Course id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 50, 83, 13);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 303, 0, 0);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Course Name: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 100, 91, 21);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Course Code: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 160, 91, 10);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Credit Hour: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 210, 82, 13);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Semester No: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 280, 82, 13);

        adbutton.setText("Add");
        adbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(adbutton);
        adbutton.setBounds(380, 330, 95, 23);

        cname.setBackground(new java.awt.Color(227, 255, 255));
        getContentPane().add(cname);
        cname.setBounds(360, 130, 140, 20);

        cid.setBackground(new java.awt.Color(223, 255, 255));
        getContentPane().add(cid);
        cid.setBounds(360, 70, 140, 20);

        ccode.setBackground(new java.awt.Color(230, 255, 255));
        getContentPane().add(ccode);
        ccode.setBounds(360, 180, 140, 20);

        chr.setBackground(new java.awt.Color(224, 255, 255));
        getContentPane().add(chr);
        chr.setBounds(450, 210, 30, 20);

        csem.setBackground(new java.awt.Color(226, 255, 255));
        getContentPane().add(csem);
        csem.setBounds(460, 280, 30, 20);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 330, 90, 23);

        csec.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(csec);
        csec.setBounds(510, 240, 70, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Choose number of sections:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 243, 140, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 770, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbuttonActionPerformed
        // TODO add your handling code here:
        
        //cid.getText(); cname.getText() ; ccode.getText(); chr.getText(); csem.getText();
        
        try 
        {
            String Name = cname.getText();
            String code = ccode.getText();
            if(Name.length() == 0 || code.length() == 0 || cid.getText().length()==0 || chr.getText().length() == 0 || csem.getText().length() == 0)
            {
                 JOptionPane.showMessageDialog(null,"Enter data in all Fields ! ");
            }
            else
            {
            int id = Integer.parseInt(cid.getText());
            int cr = Integer.parseInt(chr.getText());
            int sem = Integer.parseInt(csem.getText());
           
            Course newCourse = new Course(id,Name,code,cr,sem);
            int numberofSections = Integer.parseInt(csec.getSelectedItem());
            
            
           int r = conobject.addaNewCourse(newCourse,numberofSections);
           if(r == -1)
           {
                JOptionPane.showMessageDialog(null,"Each Course Id should be Unique, this Id already exists ! ");
           }
           else
           {
               this.setVisible(false);
               this.makeFrame();
               this.setVisible(true);
               
           }
                
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Enter only integer in integer field !! ");
        }
        
    }//GEN-LAST:event_adbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        officerFrame of = new officerFrame();
        of.setVisible(true);
        of.populateFrame(Integer.parseInt(rolinput.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    public void makeFrame()
    {
        rolinput.setText(String.valueOf(gc.officer.getId()));
        ArrayList<String> all = conobject.viewAllCourses();
        
        DefaultListModel mod = new DefaultListModel();
        for(int i=0;i<all.size();i++)
        {
            mod.addElement(all.get(i));
        }
        
        clist.setModel(mod);
        
        csec.removeAll();
        for(int i=1;i<4;i++)
        {
            csec.add(String.valueOf(i));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCourseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCourseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCourseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCourseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCourseframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adbutton;
    private javax.swing.JTextField ccode;
    private javax.swing.JTextField chr;
    private javax.swing.JTextField cid;
    private javax.swing.JList<String> clist;
    private javax.swing.JTextField cname;
    private java.awt.Choice csec;
    private javax.swing.JTextField csem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rolinput;
    // End of variables declaration//GEN-END:variables

}
