/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;


/**
 *
 * @author Usman
 */
public class addcourses extends javax.swing.JFrame {

    
     private DBConnect conobject= DBConnect.getInstance();
     GlobalClass gc = new GlobalClass();
     ArrayList<Section> SecObj = new ArrayList<Section>();
     
    /** Creates new form addcourses */
    public addcourses() {
       
        initComponents();

        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addcode = new javax.swing.JLabel();
        addsection = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selectedcourse = new java.awt.Choice();
        selectedsection = new java.awt.Choice();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        secav = new javax.swing.JButton();
        reg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Roll No: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 4, 50, 13);

        rolinput.setText("rr");
        getContentPane().add(rolinput);
        rolinput.setBounds(80, 0, 80, 22);

        jList1.setBackground(new java.awt.Color(153, 204, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 125, 218, 190);

        addcode.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        addcode.setText("Choose Course : ");
        getContentPane().add(addcode);
        addcode.setBounds(238, 125, 110, 13);

        addsection.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        addsection.setText("Choose Section:");
        getContentPane().add(addsection);
        addsection.setBounds(240, 220, 130, 23);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 300, 90, 23);

        selectedcourse.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(selectedcourse);
        selectedcourse.setBounds(238, 149, 220, 20);

        selectedsection.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(selectedsection);
        selectedsection.setBounds(240, 250, 170, 20);

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(10, 390, 90, 23);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Registration Period: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 150, 29);

        secav.setText("Show Available Sections");
        secav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secavActionPerformed(evt);
            }
        });
        getContentPane().add(secav);
        secav.setBounds(240, 180, 160, 23);

        reg.setText("..");
        getContentPane().add(reg);
        reg.setBounds(180, 60, 60, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 750, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String code = selectedcourse.getSelectedItem();
        String sec = selectedsection.getSelectedItem();
        
         Section S = conobject.getSectionObject(code,sec);
      //   System.out.println("sec : " + S.toString());
        ArrayList<String> Crs_id = conobject.getCourse(code);
      //  ArrayList<String> s_id = conobject.getSection(sec);
        
        Course ctoadd = new Course(Integer.parseInt(Crs_id.get(0)),Crs_id.get(2),Crs_id.get(1),Integer.parseInt(Crs_id.get(3)),Integer.parseInt(Crs_id.get(4)),SecObj);
        
       int ret = gc.currentUser.addCourse(ctoadd,S);
       if(ret == -1 )
       {
            subscriptionframe sf = new subscriptionframe();
             this.setVisible(false);
             sf.setVisible(true);
             sf.SubscribeCourse(ctoadd,S);
       }
      
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);      
        viewcourses vc = new viewcourses();
        vc.setVisible(true);
        vc.viewCourseList();
        
        
    }//GEN-LAST:event_backbuttonActionPerformed

    private void secavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secavActionPerformed
        // TODO add your handling code here:
        String s =  selectedcourse.getSelectedItem();
       ArrayList<String>  section = conobject.getAvailableSections(s);
        
       selectedsection.removeAll();
       for(int i=0;i<section.size();i++)
        {
           selectedsection.add(section.get(i));
           Section S = conobject.getSectionObject(s,section.get(i));
           SecObj.add(S);
        }
        
    }//GEN-LAST:event_secavActionPerformed

    
    public void showCourseButtons()
    {
        
        rolinput.setText(String.valueOf(gc.currentUser.getId()));
        reg.setText(gc.registration.getReg());
      
        
        ArrayList<String> course_section = conobject.ViewListofCourses(gc.currentUser.getSemester_No(),gc.currentUser);
        
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<course_section.size();i++)
        {
            model.addElement(course_section.get(i));
        }
        
        jList1.setModel(model);
        
        ArrayList<String>  course_Id = conobject.getCourseName(gc.currentUser.getSemester_No());
        for(int i=0;i<course_Id.size();i++)
        {
           selectedcourse.add(course_Id.get(i));
        }
       
       
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addcode;
    private javax.swing.JLabel addsection;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel rolinput;
    private javax.swing.JButton secav;
    private java.awt.Choice selectedcourse;
    private java.awt.Choice selectedsection;
    // End of variables declaration//GEN-END:variables

}
