/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;
/**
 * 
 */
/**
 *
 * @author Usman
 */
public class addGrades extends javax.swing.JFrame {

    
      Course co;
    Section se;
    GlobalClass gc = new GlobalClass();
     private DBConnect conobject= DBConnect.getInstance();
     
    /** Creates new form addGrades */
    public addGrades() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        slist = new javax.swing.JList<>();
        grade = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(751, 481));
        getContentPane().setLayout(null);

        cinfo.setText("..");
        getContentPane().add(cinfo);
        cinfo.setBounds(10, 49, 158, 14);

        slist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(slist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 95, 190, 281);
        getContentPane().add(grade);
        grade.setBounds(300, 140, 40, 20);

        jLabel2.setText("Choose Grade : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 143, 106, 14);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 140, 84, 23);

        back.setText("Back ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 421, 85, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        teachercoures tc = new teachercoures();
        tc.setVisible(true);
        tc.ShowCourses();
        
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //add button
         String s = slist.getSelectedValue();
        if ( s ==  null)
        {
             JOptionPane.showMessageDialog(null,"Select a Student first ");
        }
        
        else
        {
        char ar[] = s.toCharArray();
            int length = 0;
            for(int i=0;i<s.length();i++)
            {  
                if(ar[i]==' ')
                {
                    length = i;
                    break;
                }
            }
            char r[] = new char[length];
            for(int i=0;i<length;i++)
            {
               r[i]=ar[i];
            }
            String roll= String.valueOf(r);
            length = Integer.parseInt(roll);
            Student S = conobject.populatestudentFrame(length);
            String gr = grade.getSelectedItem();
            
            gc.currentTeacher.assignGrade(S,co,se,gr);
             
             
             
             
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showRegs(String c, String s)
    {
        cinfo.setText(c + " " + s);
        grade.add("A+");
        grade.add("A");
        grade.add("A-");
        grade.add("B+");
        grade.add("B");
        grade.add("B-");
        grade.add("C+");
        grade.add("C");
        grade.add("C-");
        grade.add("D+");
        grade.add("D");
        grade.add("D-");
        grade.add("F");
        
       
        ArrayList<String> Crs_id = conobject.getCourse(c);
      
        co = new Course(Integer.parseInt(Crs_id.get(0)),Crs_id.get(2),Crs_id.get(1),Integer.parseInt(Crs_id.get(3)),Integer.parseInt(Crs_id.get(4)));
        
        se = conobject.getSectionObject(c,s);
        
        
        DefaultListModel mod = new DefaultListModel();
        mod.clear();
        for(int i=0;i<se.getregs().size();i++)
        {
            mod.addElement(se.getregs().get(i).toString());
        }
        slist.setModel(mod);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cinfo;
    private java.awt.Choice grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> slist;
    // End of variables declaration//GEN-END:variables

}
