/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;

/**
 *
 * @author Usman
 */
public class dropcourses extends javax.swing.JFrame {

    private DBConnect conobject= DBConnect.getInstance();
    GlobalClass gc = new GlobalClass();
    
    /** Creates new form dropcourses */
    public dropcourses() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registercourseslist = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        choosencourse = new java.awt.Choice();
        dropbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wdate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Roll No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 54, 13);

        rolinput.setText("...");
        getContentPane().add(rolinput);
        rolinput.setBounds(70, 12, 93, 14);

        registercourseslist.setBackground(new java.awt.Color(153, 204, 255));
        registercourseslist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(registercourseslist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 108, 257, 220);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Your Registered Courses: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 83, 170, 14);

        choosencourse.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(choosencourse);
        choosencourse.setBounds(277, 120, 200, 20);

        dropbutton.setText("Drop");
        dropbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));
        dropbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(dropbutton);
        dropbutton.setBounds(277, 150, 73, 20);

        backbutton.setText("Back");
        backbutton.setBorder(new javax.swing.border.MatteBorder(null));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(10, 380, 73, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("Withdrawal :  ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 45, 140, 14);

        wdate.setText("..");
        getContentPane().add(wdate);
        wdate.setBounds(200, 44, 110, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 760, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);      
        viewcourses vc = new viewcourses();
        vc.setVisible(true);
        vc.viewCourseList();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void dropbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropbuttonActionPerformed
        // TODO add your handling code here:
        int stud = gc.currentUser.getId();
        String course = choosencourse.getSelectedItem();
         ArrayList<String>  section = conobject.getAvailableSections(course);
        
       ArrayList<Section> SecObj = new ArrayList<Section>();
       for(int i=0;i<section.size();i++)
        {
           Section S = conobject.getSectionObject(course,section.get(i));
           SecObj.add(S);
        }
        
        
        ArrayList<String> Crs_id = conobject.getCourse(course);  
        Course ctoDrop = new Course(Integer.parseInt(Crs_id.get(0)),Crs_id.get(2),Crs_id.get(1),Integer.parseInt(Crs_id.get(3)),Integer.parseInt(Crs_id.get(4)),SecObj);

        int section2 = conobject.getSectionId(stud,ctoDrop.getCourseid());
        for(int i=0;i<section.size();i++)
        {
           if(SecObj.get(i).getID() == section2)
           {
               section2 = i;
           }
        }
        
        int ret = gc.currentUser.dropCourse(ctoDrop,SecObj.get(section2));
        if(ret == 1)
        {
            
            conobject.checkForSubscribedStudent(ctoDrop,SecObj.get(section2));
            
            
        }
        
        
        
        this.setVisible(false);
        
         
        this.setVisible(true);  
        this.showStd_Courses();
        
    }//GEN-LAST:event_dropbuttonActionPerformed

    public void showStd_Courses()
    {
        rolinput.setText(String.valueOf(gc.currentUser.getId()));
        wdate.setText(gc.registration.getWdate());
        DefaultListModel model = new DefaultListModel();
        choosencourse.removeAll();
        
            for(int i=0;i<gc.currentUser.getCourses().size();i++)
             {
                 if(gc.currentUser.getCourses(i).getSemester_no() == gc.currentUser.getSemester_No())
                 {
                 choosencourse.add(gc.currentUser.getCourses(i).getCourseName());      
                  model.addElement(gc.currentUser.getCourses(i).getCourseName());    
                 }
             } 
             if(gc.currentUser.getSemester_No() > 1)
            {
            
            for(int i=0;i<gc.currentUser.getTrans().getCourses().size();i++)
            {
              if(gc.currentUser.getTrans().getGrades().get(i).equals("F") && gc.currentUser.getCourses().get(i).getSemester_no() == (gc.currentUser.getSemester_No()-1))
               {
                  choosencourse.add(gc.currentUser.getCourses(i).getCourseName());      
                  model.addElement(gc.currentUser.getCourses(i).getCourseName()); 
               }
            }
            
            
            }
            
             registercourseslist.setModel(model);
             
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dropcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dropcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dropcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dropcourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dropcourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private java.awt.Choice choosencourse;
    private javax.swing.JButton dropbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> registercourseslist;
    private javax.swing.JLabel rolinput;
    private javax.swing.JLabel wdate;
    // End of variables declaration//GEN-END:variables

}
