/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author Usman
 */
public class LoginFrame extends javax.swing.JFrame {

    private DBConnect conobject= DBConnect.getInstance();
    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        student = new javax.swing.JRadioButton();
        officer = new javax.swing.JRadioButton();
        teacher = new javax.swing.JRadioButton();
        password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setText("Roll No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 140, 50, 14);

        username.setBackground(new java.awt.Color(153, 204, 255));
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(10, 170, 166, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("Password: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 80, 20);

        login.setBackground(new java.awt.Color(102, 204, 255));
        login.setForeground(new java.awt.Color(0, 51, 204));
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(40, 270, 93, 20);

        student.setBackground(new java.awt.Color(102, 204, 255));
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        getContentPane().add(student);
        student.setBounds(120, 10, 93, 23);

        officer.setBackground(new java.awt.Color(102, 204, 255));
        officer.setText("Academic Officer");
        officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officerActionPerformed(evt);
            }
        });
        getContentPane().add(officer);
        officer.setBounds(230, 10, 160, 23);

        teacher.setBackground(new java.awt.Color(102, 204, 255));
        teacher.setText("Teacher");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        getContentPane().add(teacher);
        teacher.setBounds(10, 10, 93, 23);

        password.setBackground(new java.awt.Color(153, 204, 255));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        getContentPane().add(password);
        password.setBounds(10, 230, 166, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usman\\Pictures\\Screenshots\\robot.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String myUsername=username.getText();
        String myPassword = password.getText();
        
        try
        {
        int u=Integer.parseInt(myUsername);
        

        if( student.isSelected()==true){
            if(conobject.verifystudent(u, myPassword) == 1) {

                JOptionPane.showMessageDialog(null,"login sucessfull.");
                this.setVisible(false);

                studentframe sf = new studentframe();
                sf.setVisible(true);

                sf.populateFrame(u);

            }
            else if(conobject.verifystudent(u, myPassword) == 0) {
                JOptionPane.showMessageDialog(null,"login  \n unsucessfull.");
            }
            else {
                JOptionPane.showMessageDialog(null,"an exception occured");
            }

        }

        else   if( teacher.isSelected()==true){
            if(conobject.verifyteacher(u, myPassword) == 1) {

                JOptionPane.showMessageDialog(null,"login sucessfull.");
                this.setVisible(false);

                teacherframe sf = new teacherframe();
                sf.setVisible(true);

                sf.populateFrame(u);

            }
            else if(conobject.verifyteacher(u, myPassword) == 0) {
                JOptionPane.showMessageDialog(null,"login unsucessfull.");
            }
            else {
                JOptionPane.showMessageDialog(null,"an exception occured");
            }

        }

        else   if( officer.isSelected()==true){
            if(conobject.verifyofficer(u, myPassword) == 1) {

                JOptionPane.showMessageDialog(null,"login sucessfull.");
                this.setVisible(false);

                officerFrame of = new officerFrame();
                of.setVisible(true);
                of.populateFrame(u);

            }
            else if(conobject.verifyofficer(u, myPassword) == 0) {
                JOptionPane.showMessageDialog(null,"login unsucessfull.");
            }
            else {
                JOptionPane.showMessageDialog(null,"an exception occured");
            }

        }

        else{

            JOptionPane.showMessageDialog(null,"sellect an option below");

        }
        
        } catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null,"Invalid User Id :( ");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officerActionPerformed
        // TODO add your handling code here:
        student.setSelected(false);
        teacher.setSelected(false);

    }//GEN-LAST:event_officerActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
        teacher.setSelected(false);
        officer.setSelected(false);
    }//GEN-LAST:event_studentActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        // TODO add your handling code here:

        student.setSelected(false);
        officer.setSelected(false);

    }//GEN-LAST:event_teacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JRadioButton officer;
    private javax.swing.JTextField password;
    private javax.swing.JRadioButton student;
    private javax.swing.JRadioButton teacher;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
