/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;
/**
 *
 * @author Usman
 */
public class studAttendance extends javax.swing.JFrame {

    
      private DBConnect conobject= DBConnect.getInstance();
    GlobalClass gc = new GlobalClass();
    DefaultListModel model = new DefaultListModel();
    
    /** Creates new form studAttendance */
    public studAttendance() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clist = new java.awt.Choice();
        showbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attlist = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        clist.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(clist);
        clist.setBounds(0, 61, 150, 20);

        showbutton.setBackground(new java.awt.Color(153, 204, 255));
        showbutton.setText("Show Attendance");
        showbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showbutton);
        showbutton.setBounds(0, 103, 130, 19);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Roll No: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 12, 63, 13);

        rolinput.setText("..");
        getContentPane().add(rolinput);
        rolinput.setBounds(73, 11, 84, 14);

        attlist.setBackground(new java.awt.Color(153, 204, 255));
        attlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(attlist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(218, 61, 263, 302);

        jLabel2.setFont(new java.awt.Font("Gadugi", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Attendance");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 30, 130, 25);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 312, 100, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        jLabel3.setText(".");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1, -9, 780, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
        String course = clist.getSelectedItem();
        ArrayList<Attendance> atd = new ArrayList<Attendance>();
        
         ArrayList<String> Crs_id = conobject.getCourse(course);  
        Course crs = new Course(Integer.parseInt(Crs_id.get(0)),Crs_id.get(2),Crs_id.get(1),Integer.parseInt(Crs_id.get(3)),Integer.parseInt(Crs_id.get(4)));
        

        
               atd = gc.currentUser.viewAttendance(crs);
                
       
        model.clear();
        model.addElement("     Date      |  Presence  ");
        if(atd.size() == 0)
        {
            model.addElement("     Nothing to Show!   ");
            attlist.setModel(model);
        }
             else
        {
            int a =0;
        for(int i=0;i<atd.size();i++)
        {
            if(atd.get(i).getStid() == gc.currentUser.getId() && atd.get(i).getsem() == gc.currentUser.getSemester_No())
            {
            model.addElement("  " + atd.get(i).getDate() + "  |   " + atd.get(i).getstatus()); 
            a++;
            }
            
        }
        if(a==0)
        {
             model.addElement("     Nothing to Show!   ");
        }
        
        attlist.setModel(model);
        }
    }//GEN-LAST:event_showbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        studentframe sf = new studentframe();
        sf.setVisible(true);
        sf.populateFrame(gc.currentUser.getId());
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showAttendance()
    {
        rolinput.setText(String.valueOf(gc.currentUser.getId()));
        
        
        
        clist.removeAll();
        
            for(int i=0;i<gc.currentUser.getCourses().size();i++)
             {
                 if(gc.currentUser.getCourses().get(i).getSemester_no() == gc.currentUser.getSemester_No())
                 {
                 clist.add(gc.currentUser.getCourses(i).getCourseName());           
                 } 
             } 
             for(int i=0;i<gc.currentUser.getTrans().getCourses().size();i++)
            {
              if(gc.currentUser.getTrans().getGrades().get(i).equals("F") && gc.currentUser.getCourses().get(i).getSemester_no() == (gc.currentUser.getSemester_No()-1))
               {
                 clist.add(gc.currentUser.getCourses(i).getCourseName());  
               }
            }
            
            model.addElement("     Date      |  Presence  ");
             attlist.setModel(model);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> attlist;
    private java.awt.Choice clist;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rolinput;
    private javax.swing.JButton showbutton;
    // End of variables declaration//GEN-END:variables

}
