/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usman
 */
public class studentframe extends javax.swing.JFrame {

    
    private DBConnect conobject= DBConnect.getInstance();
     GlobalClass gc = new GlobalClass();
    
    /** Creates new form studentframe */
    public studentframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewcourse = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        semnumber = new javax.swing.JLabel();
        nameinput = new javax.swing.JLabel();
        rollinput = new javax.swing.JLabel();
        emailinput = new javax.swing.JLabel();
        phoneinput = new javax.swing.JLabel();
        seminput = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        notification = new javax.swing.JLabel();
        notify = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        viewtranscript = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        viewcourse.setText("View Courses List");
        viewcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcourseActionPerformed(evt);
            }
        });
        getContentPane().add(viewcourse);
        viewcourse.setBounds(10, 330, 150, 23);

        name.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        name.setText("Name:");
        getContentPane().add(name);
        name.setBounds(10, 69, 60, 17);

        id.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        id.setText("Roll No:");
        getContentPane().add(id);
        id.setBounds(10, 100, 60, 17);

        email.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        email.setText("Email:");
        getContentPane().add(email);
        email.setBounds(10, 130, 50, 17);

        phone.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        phone.setText("Phone No:");
        getContentPane().add(phone);
        phone.setBounds(290, 70, 80, 19);

        semnumber.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        semnumber.setText("Semester No:");
        getContentPane().add(semnumber);
        semnumber.setBounds(290, 100, 110, 17);

        nameinput.setText("name");
        getContentPane().add(nameinput);
        nameinput.setBounds(100, 70, 100, 14);

        rollinput.setText("roll");
        getContentPane().add(rollinput);
        rollinput.setBounds(100, 100, 80, 14);

        emailinput.setText("email");
        getContentPane().add(emailinput);
        emailinput.setBounds(100, 130, 185, 14);

        phoneinput.setText("0900");
        getContentPane().add(phoneinput);
        phoneinput.setBounds(390, 70, 100, 14);

        seminput.setText("sem");
        getContentPane().add(seminput);
        seminput.setBounds(400, 100, 60, 14);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Welcome To Online LMS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 240, 30);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(470, 10, 110, 22);

        notification.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        notification.setText("NOTIFICATION: ");
        getContentPane().add(notification);
        notification.setBounds(10, 190, 140, 17);

        notify.setText("...");
        getContentPane().add(notify);
        notify.setBounds(150, 160, 300, 70);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(567, 135, 0, 0);

        jButton1.setText("View Attendance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 330, 130, 23);

        jButton2.setText("Mark as read");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 220, 150, 23);

        viewtranscript.setText("View Transcript");
        viewtranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(viewtranscript);
        viewtranscript.setBounds(320, 330, 110, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcourseActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);      
        viewcourses vc = new viewcourses();
        vc.setVisible(true);
        vc.viewCourseList();
        
    }//GEN-LAST:event_viewcourseActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
         JOptionPane.showMessageDialog(null,"You Logged Out of System !");
         new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(gc.currentUser.getCourses().size()==0)
        {
            JOptionPane.showMessageDialog(null,"You have no registered Courses to view Attendance !! "); 
        
        }
        else
        {
        this.setVisible(false);
        studAttendance sa = new studAttendance();
        sa.setVisible(true);
        sa.showAttendance();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        notify.setText("No new Notification for you !!! ");
        conobject.setNoti(gc.currentUser.getId(),"No new Notification for you !!!");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewtranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtranscriptActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        transcriptframe tr = new transcriptframe();
        tr.setVisible(true);
        tr.showTranscript();
        
    }//GEN-LAST:event_viewtranscriptActionPerformed

    
    public void populateFrame(int id)
    {
        gc.currentUser = new Student();
        gc.currentUser = conobject.populatestudentFrame(id);
        
        
        ArrayList<String> date = conobject.getRegistrationInfo(gc.currentUser.getSemester_No());
         
      
           
        
        gc.registration = new RegPeriod(date.get(0),date.get(1),Integer.parseInt(date.get(2)));
        
        rollinput.setText(String.valueOf(gc.currentUser.getId()));
        nameinput.setText(gc.currentUser.getName());
        emailinput.setText(gc.currentUser.getEmail());
        phoneinput.setText(gc.currentUser.getPhone());
        seminput.setText(String.valueOf(gc.currentUser.getSemester_No()));
        notify.setText(gc.currentUser.getNotification());
        
//         System.out.println(gc.registration.getReg());
//         System.out.println(gc.registration.getReg().length());
//            System.out.println("\n");
        
//            for(int i=0;i<gc.currentUser.getTrans().getCourses().size();i++)
//            {
//                System.out.println(gc.currentUser.getTrans().getCourses().get(i).getCourseName()+"\n");
//                 System.out.println(gc.currentUser.getTrans().getGrades().get(i)+"\n");
//            }

//if(gc.currentUser.getSemester_No() > 1)
//{
//            
//             for(int i=0;i<gc.currentUser.getTrans().getCourses().size();i++)
//            {
//              if(gc.currentUser.getTrans().getGrades().get(i).equals("F") && gc.currentUser.getCourses().get(i).getSemester_no() == (gc.currentUser.getSemester_No()-1))
//               {
//                    conobject.addCourseinGrade(gc.currentUser.getId(),gc.currentUser.getSemester_No(),gc.currentUser.getCourses().get(i).getCourseid(),"I");
//               }
//            }
//            
//}
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailinput;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameinput;
    private javax.swing.JLabel notification;
    private javax.swing.JLabel notify;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phoneinput;
    private javax.swing.JLabel rollinput;
    private javax.swing.JLabel seminput;
    private javax.swing.JLabel semnumber;
    private javax.swing.JButton viewcourse;
    private javax.swing.JButton viewtranscript;
    // End of variables declaration//GEN-END:variables

}
