/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;

/**
 *
 * @author Usman
 */
public class subscriptionframe extends javax.swing.JFrame {

    private DBConnect conobject= DBConnect.getInstance();
    GlobalClass gc = new GlobalClass();
    Section S1 = new Section();
    Course c = new Course();
    /** Creates new form subscriptionframe */
    public subscriptionframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yesoption = new javax.swing.JRadioButton();
        nooption = new javax.swing.JRadioButton();
        clickbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        courseid = new javax.swing.JLabel();
        secid = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Oh! We are sad that no more Space left for you in this section.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 33, 400, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Do you want to subscribe to this course's section ? ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 390, 17);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("So we will notify you if we will have spae for you ... :)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 410, 20);

        yesoption.setBackground(new java.awt.Color(0, 0, 0));
        yesoption.setForeground(new java.awt.Color(255, 255, 255));
        yesoption.setText("Yes");
        yesoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesoptionActionPerformed(evt);
            }
        });
        getContentPane().add(yesoption);
        yesoption.setBounds(10, 170, 93, 23);

        nooption.setBackground(new java.awt.Color(0, 0, 0));
        nooption.setForeground(new java.awt.Color(255, 255, 255));
        nooption.setText("No");
        nooption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nooptionActionPerformed(evt);
            }
        });
        getContentPane().add(nooption);
        nooption.setBounds(120, 170, 93, 23);

        clickbutton.setBackground(new java.awt.Color(51, 51, 51));
        clickbutton.setText("Select");
        clickbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clickbutton);
        clickbutton.setBounds(240, 170, 73, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll No:  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 60, 14);

        rolinput.setText("..");
        getContentPane().add(rolinput);
        rolinput.setBounds(60, 10, 60, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course Id: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 60, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Section Id: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 120, 70, 20);

        courseid.setBackground(new java.awt.Color(0, 0, 0));
        courseid.setForeground(new java.awt.Color(255, 255, 255));
        courseid.setText("..");
        getContentPane().add(courseid);
        courseid.setBounds(80, 120, 60, 14);

        secid.setBackground(new java.awt.Color(0, 0, 0));
        secid.setForeground(new java.awt.Color(255, 255, 255));
        secid.setText("..");
        getContentPane().add(secid);
        secid.setBounds(230, 120, 60, 20);

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(10, 390, 73, 23);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(454, 334, 60, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj2.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-6, -6, 760, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yesoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesoptionActionPerformed
        // TODO add your handling code here:
        nooption.setSelected(false);
    }//GEN-LAST:event_yesoptionActionPerformed

    private void nooptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nooptionActionPerformed
        // TODO add your handling code here:
        yesoption.setSelected(false);
    }//GEN-LAST:event_nooptionActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        addcourses c_add = new addcourses();
        c_add.setVisible(true);c_add.showCourseButtons();
        
        
    }//GEN-LAST:event_backbuttonActionPerformed

    private void clickbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickbuttonActionPerformed
        // TODO add your handling code here:
        if(yesoption.isSelected()==true)
        {
           int rol = gc.currentUser.getId();
           int cour = Integer.parseInt(courseid.getText());
           int sec = Integer.parseInt(secid.getText());
           //int rows = conobject.addSubscription(rol,cour,sec);
           
               JOptionPane.showMessageDialog(null,"You are added to subscription list of this course !!! ");
               conobject.incrementCurrentCourses(gc.currentUser.getId());
               gc.currentUser.setNumberofcourses( gc.currentUser.getNumberofcourses()+1);
               //S1.sub_students.add(gc.currentUser);
               
               gc.currentUser.addSubscription(c,S1);
           
           this.setVisible(false);    
           addcourses c_add = new addcourses();
           c_add.setVisible(true);
           c_add.showCourseButtons();
           
        }
        else if(nooption.isSelected()==true)
        {
             this.setVisible(false);    
             addcourses c_add = new addcourses();
             c_add.setVisible(true);
             c_add.showCourseButtons();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select an Option !! ");
        }
    }//GEN-LAST:event_clickbuttonActionPerformed

    public void SubscribeCourse(Course course, Section S)
    {
        c = course;
        S1 =S;
        int sectionId = S.getID();
        rolinput.setText(String.valueOf(gc.currentUser.getId()));
        courseid.setText(String.valueOf(course.getCourseid()));
        secid.setText(String.valueOf(sectionId));
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subscriptionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subscriptionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subscriptionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subscriptionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subscriptionframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton clickbutton;
    private javax.swing.JLabel courseid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton nooption;
    private javax.swing.JLabel rolinput;
    private javax.swing.JLabel secid;
    private javax.swing.JRadioButton yesoption;
    // End of variables declaration//GEN-END:variables

}
