/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;
/**
 *
 * @author Usman
 */
public class teachercoures extends javax.swing.JFrame {
   
    GlobalClass gc = new GlobalClass();
    /** Creates new form teachercoures */
    public teachercoures() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        clist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(clist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(61, 91, 219, 272);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Courses you are teaching :  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 67, 176, 13);

        jButton1.setText("Add Attendance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(439, 131, 161, 23);

        jButton2.setText("Assign Final Grades");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(439, 165, 161, 23);

        jButton3.setText("Add Evaluation/Marks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(439, 206, 161, 23);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(18, 413, 105, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //add attendance 
        
        String s = clist.getSelectedValue();
       // selectedlabel.setText(s);
       if(s == null)
       {
            JOptionPane.showMessageDialog(null,"Select a course first! ");
       }
       else
       {
       
       int ind = s.indexOf("CS_A");
       int ind1 = s.indexOf("CS_B");
       int ind2 = s.indexOf("CS_C");
       
       if(ind > -1)
       {
       char s1[] = s.toCharArray();
       char c[] = new char[ind-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        System.out.println(crs+" "+sec);
        
        this.setVisible(false);
        addAttend at = new addAttend();
        at.setVisible(true);
        at.showRegs(crs,sec);
        
       }
       else if(ind1 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind1-1];
       char s2[] = new char[s.length()- ind1];
       for(int i=0;i<ind1-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind1;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
           
        this.setVisible(false);
        addAttend at = new addAttend();
        at.setVisible(true);
        at.showRegs(crs,sec);
       }
       else if(ind2 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind2-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind2-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind2;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
        this.setVisible(false);
        addAttend at = new addAttend();
        at.setVisible(true);
        at.showRegs(crs,sec);
           
       }
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

                teacherframe sf = new teacherframe();
                sf.setVisible(true);

                sf.populateFrame(gc.currentTeacher.getId());
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String s = clist.getSelectedValue();
       // selectedlabel.setText(s);
       if(s == null)
       {
            JOptionPane.showMessageDialog(null,"Select a course first! ");
       }
       else
       {
       
       int ind = s.indexOf("CS_A");
       int ind1 = s.indexOf("CS_B");
       int ind2 = s.indexOf("CS_C");
       
       if(ind > -1)
       {
       char s1[] = s.toCharArray();
       char c[] = new char[ind-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        System.out.println(crs+" "+sec);
        
        this.setVisible(false);
        setevaluations st = new setevaluations();
        st.setVisible(true);
        st.showRegs(crs,sec);
        
       }
       else if(ind1 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind1-1];
       char s2[] = new char[s.length()- ind1];
       for(int i=0;i<ind1-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind1;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
           
      this.setVisible(false);
        setevaluations st = new setevaluations();
        st.setVisible(true);
        st.showRegs(crs,sec);
       }
       else if(ind2 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind2-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind2-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind2;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
         this.setVisible(false);
        setevaluations st = new setevaluations();
        st.setVisible(true);
        st.showRegs(crs,sec);
       }
        
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //add grades 
           
        String s = clist.getSelectedValue();
       // selectedlabel.setText(s);
       if(s == null)
       {
            JOptionPane.showMessageDialog(null,"Select a course first! ");
       }
       else
       {
       
       int ind = s.indexOf("CS_A");
       int ind1 = s.indexOf("CS_B");
       int ind2 = s.indexOf("CS_C");
       
       if(ind > -1)
       {
       char s1[] = s.toCharArray();
       char c[] = new char[ind-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        System.out.println(crs+" "+sec);
        
        this.setVisible(false);
        addGrades at = new addGrades();
        at.setVisible(true);
        at.showRegs(crs,sec);
        
       }
       else if(ind1 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind1-1];
       char s2[] = new char[s.length()- ind1];
       for(int i=0;i<ind1-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind1;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
           
        this.setVisible(false);
       addGrades at = new addGrades();
        at.setVisible(true);
        at.showRegs(crs,sec);
       }
       else if(ind2 > -1)
       {
            char s1[] = s.toCharArray();
       char c[] = new char[ind2-1];
       char s2[] = new char[s.length()- ind];
       for(int i=0;i<ind2-1;i++)
       {
           c[i] = s1[i];
       }
       
      // System.out.println("___________-----------");
       int j=0;
        for(int i=ind2;i<s.length();i++)
       {
           s2[j] = s1[i];  j++;
       }
        
        String crs = String.valueOf(c);
        String sec = String.valueOf(s2);
        
        //System.out.println(crs+" "+sec);
        
        this.setVisible(false);
       addGrades at = new addGrades();
        at.setVisible(true);
        at.showRegs(crs,sec);
       }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    }
    public void ShowCourses()
    {
        DefaultListModel mod = new DefaultListModel();
        mod.clear();
         for(int i=0;i<gc.currentTeacher.getCourses().size();i++)
        {
            mod.addElement(gc.currentTeacher.getCourses().get(i).getCourseName()+" "+gc.currentTeacher.getsections().get(i).getname());
            //System.out.println(gc.currentTeacher.getsections().get(i).toString());
        }
         clist.setModel(mod);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teachercoures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teachercoures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teachercoures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teachercoures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teachercoures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> clist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
