/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsda;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.*;
import java.text.SimpleDateFormat;  
import java.util.Date; 
import java.sql.*; 
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.*; 
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
import javax.swing.table.DefaultTableModel;  
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.util.ArrayList;
/**
 *
 * @author Usman
 */
public class transcriptframe extends javax.swing.JFrame {

     GlobalClass gc = new GlobalClass();
     private DBConnect conobject= DBConnect.getInstance();
     
    /** Creates new form transcriptframe */
    public transcriptframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        rolinput = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(null);

        tlist.setBackground(new java.awt.Color(153, 204, 255));
        tlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(tlist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 64, 286, 359);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Roll No: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 12, 58, 13);

        rolinput.setText("..");
        getContentPane().add(rolinput);
        rolinput.setBounds(78, 11, 89, 14);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 400, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsda/proj.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //back 
       this.setVisible(false);
        studentframe sf = new studentframe();
        sf.setVisible(true);
        sf.populateFrame(gc.currentUser.getId());
             
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showTranscript()
    {
        double mul = 0;
        int sum = 0;
        rolinput.setText(String.valueOf(gc.currentUser.getId()));
        
        DefaultListModel mod = new DefaultListModel();
        mod.clear();
        
        
        //else if(gc.currentUser.getSemester_No()>1)
        
            ArrayList<Double> sgpa = new ArrayList<Double>();
            ArrayList<Double> cgpa = new ArrayList<Double>();
            
            
            for(int j=1;j<=gc.currentUser.getSemester_No();j++)
            {
                mul =0; sum =0;
                mod.addElement("SEMESTER # "+ j);
                for(int i=0;i<gc.currentUser.getTrans().getCourses().size();i++)
                {
                    if(gc.currentUser.getTrans().getCourses().get(i).getSemester_no() == j)
                    {
            mod.addElement(gc.currentUser.getTrans().getCourses().get(i).getCourseName()+ " : "+  gc.currentUser.getTrans().getGrades().get(i));
            if(gc.currentUser.getTrans().getGrades().get(i).equals("A+") || gc.currentUser.getTrans().getGrades().get(i).equals("A"))
            {
                mul = mul + (4*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("A-"))
            {
                mul = mul + (3.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("B+"))
            {
                mul = mul + (3.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("B"))
            {
                mul = mul + (3*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("B-"))
            {
                mul = mul + (2.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("C+"))
            {
                mul = mul + (2.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           else  if(gc.currentUser.getTrans().getGrades().get(i).equals("C") )
            {
                mul = mul + (2*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("C-"))
            {
                mul = mul + (1.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           else  if(gc.currentUser.getTrans().getGrades().get(i).equals("D+") )
            {
                mul = mul + (1.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("D") )
            {
                mul = mul + (1*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("D-"))
            {
                mul = mul + (0.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(gc.currentUser.getTrans().getGrades().get(i).equals("F") )
            {
                mul = mul + (0*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           
            }
          else if(gc.currentUser.getTrans().getCourses().get(i).getSemester_no() == j-1)
           {
            if(gc.currentUser.getTrans().getGrades().get(i).equals("F"))
             {
     
               String str = conobject.getGrade(gc.currentUser.getId(),gc.currentUser.getTrans().getCourses().get(i).getCourseid(),gc.currentUser.getSemester_No());
                if(str.equals(" "))
                 {
                   mod.addElement(gc.currentUser.getTrans().getCourses().get(i).getCourseName()+ " :   I");
                 }
                 else
               {
              mod.addElement(gc.currentUser.getTrans().getCourses().get(i).getCourseName()+ " :  "+ str);
             if(str.equals("A+") || str.equals("A"))
            {
                mul = mul + (4*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("A-"))
            {
                mul = mul + (3.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("B+"))
            {
                mul = mul + (3.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("B"))
            {
                mul = mul + (3*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("B-"))
            {
                mul = mul + (2.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("C+"))
            {
                mul = mul + (2.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           else  if(str.equals("C") )
            {
                mul = mul + (2*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("C-"))
            {
                mul = mul + (1.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           else  if(str.equals("D+") )
            {
                mul = mul + (1.33*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("D") )
            {
                mul = mul + (1*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("D-"))
            {
                mul = mul + (0.67*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
            else if(str.equals("F") )
            {
                mul = mul + (0*gc.currentUser.getTrans().getCourses().get(i).getCr_hr());
                sum =sum+gc.currentUser.getTrans().getCourses().get(i).getCr_hr();
            }
           
                                 
                                 
      }
                            
      }
                    
       }
        
         }
                 DecimalFormat D = new DecimalFormat("#.00");
                 if(sum==0)
                 {
                     sgpa.add(0.00);
                    cgpa.add(0.00);
                     mod.addElement("SGPA:  "+ String.valueOf(0.00) + " |  CGPA:  " + String.valueOf(0.00) );
                    mod.addElement("---------------------------------------------------------------");
                    tlist.setModel(mod);
                 }
                 else
                 {
                double gpa = mul/sum;
                if(j==1)
                {
                    sgpa.add(gpa);
                    cgpa.add(gpa);
                    mod.addElement("SGPA:  "+ String.valueOf(D.format(gpa)) + " |  CGPA:  " + String.valueOf(D.format(gpa)) );
                    mod.addElement("---------------------------------------------------------------");
                    tlist.setModel(mod);
                    conobject.setGpas(gc.currentUser.getId(),j,String.valueOf(D.format(gpa)),String.valueOf(D.format(gpa)));
                }
                else
                {
                    double sgpa2 = gpa;
                     double sum2=0;
                     sgpa.add(gpa);
                    for(int k=0;k<sgpa.size();k++)
                    {
                       sum2 = sum2 + sgpa.get(k);
                    }
                    gpa = sum2/j;
                    cgpa.add(sum2/j);
                    mod.addElement("SGPA:  "+ String.valueOf(D.format(sgpa2)) + " |  CGPA:  " + String.valueOf(D.format(gpa)) );
                    mod.addElement("---------------------------------------------------------------");
                    tlist.setModel(mod);
                    conobject.setGpas(gc.currentUser.getId(),j,String.valueOf(D.format(sgpa2)),String.valueOf(D.format(gpa)));
                }
       
                 }
        
            
                
            } 
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transcriptframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transcriptframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transcriptframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transcriptframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transcriptframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rolinput;
    private javax.swing.JList<String> tlist;
    // End of variables declaration//GEN-END:variables

}
